---
- name: Add WireGuard repository
  get_url:
    url: "https://copr.fedorainfracloud.org/coprs/jdoss/wireguard/repo/\
      epel-{{ ansible_distribution_major_version }}/jdoss-wireguard-epel-{{ ansible_distribution_major_version }}.repo"
    dest: /etc/yum.repos.d/wireguard.repo

- name: Install EPEL repository
  yum:
    name: epel-release
    update_cache: yes
